---
# handlers file for autobuilder
- name: restart ntpd
  systemd:
    name: ntpd
    state: restarted
    enabled: yes

- name: yum clean
  command: yum clean all
  args:
    warn: no

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted

- name: restart sssd
  systemd:
    name: sssd
    state: restarted

- name: restart netflow
  systemd:
    name: nfcapd
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart web
  systemd:
    name: httpd
    state: restarted
