---
# tasks file for realm
- name: configure DNS for {{ domain }}
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: check if machine is realm bound
  shell: /bin/bash -c "realm list"
  register: realmd_bound
  changed_when: false
  ignore_errors: true

- name: join to realm
  command: /bin/bash -c "echo '{{ realm_password }}' | /usr/sbin/realm join --user={{ realm_user }}@{{ domain }} {{ domain }}"
  when: realmd_bound.stdout == ""
  no_log: true

- name: modify sssd.conf
  blockinfile:
    path: /etc/sssd/sssd.conf
    insertafter: '^\[sssd\]'
    block: |
      default_domain_suffix = {{ domain }}
      use_fully_qualified_names = False
  notify: restart sssd
  when: realmd_bound.stdout == ""

- name: restrict access
  command: /bin/bash -c "/usr/sbin/realm permit -g domain\ admins@{{ domain }}"
  when: realmd_bound.stdout == ""
    
- name: update sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%domain\ admins'
    line: '%domain\ admins ALL=(ALL) ALL'
    insertafter: '^%wheel'
    create: yes
    validate: '/sbin/visudo -cf %s'
