---
# tasks file for packages
- name: update packages
  yum:
    name: '*'
    state: latest

- name: install packages
  yum:
    name: '{{ packages }}'
    state: latest

- name: remove packages
  yum:
    name: '{{ rm_packages }}'
    state: absent
  vars:
    rm_packages:
      - cups
      - postfix
