# tasks file for esxi_datastore
---
- name: Recan HBA's for a given ESXi host and refresh storage system objects
  vmware_host_scanhba:
    hostname: '{{ item.esxi_ip_address }}'
    username: '{{ item.esxi_username }}'
    password: '{{ item.esxi_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    refresh_storage: true
    validate_certs: no
  delegate_to: localhost
  loop: "{{ esxi_servers }}"

- name: Gather info about vmhbas of an ESXi Host
  vmware_host_vmhba_info:
    hostname: '{{ item.esxi_ip_address }}'
    username: '{{ item.esxi_username }}'
    password: '{{ item.esxi_password }}'
    esxi_hostname: '{{ inventory_hostname }}'
    validate_certs: no
  register: host_vmhbas
  delegate_to: localhost
  loop: "{{ esxi_servers }}"

- name: Create and Mount VMFS datastore to ESXi
  vmware_host_datastore:
    hostname: '{{ item.esxi_ip_address }}'
    username: '{{ item.esxi_username }}'
    password: '{{ item.esxi_password }}'
    datastore_name: "{{ item.esxi_hostname }}-localdatastore"
    datastore_type: "vmfs"
    vmfs_device_name: "mpx.vmhba0:C0:T1:L0"
    vmfs_version: 6
    esxi_hostname: '{{ inventory_hostname }}'
    state: present
    validate_certs: no
  delegate_to: localhost
  loop: "{{ esxi_servers }}"

- name: Create ISO directory on local ESXi datastore
  vsphere_file:
    host: '{{ item.esxi_ip_address }}'
    username: '{{ item.esxi_username }}'
    password: '{{ item.esxi_password }}'
    #src: /other/local/file
    datacenter: ha-datacenter
    datastore: "{{ item.esxi_hostname }}-localdatastore"
    path: /ISO
    state: directory
    validate_certs: no
  delegate_to: localhost
  loop: "{{ esxi_servers }}"

- name: Copy Linux ISO to local ESXi datastore
  vsphere_copy:
    hostname: '{{ item.esxi_ip_address }}'
    username: '{{ item.esxi_username }}'
    password: '{{ item.esxi_password }}'
    src: /home/archiznix/git-novetta/autobuilder/ansible/roles/esxi_datastore/files/linux_iso
    #datacenter: DC1 Someplace
    datastore: "{{ item.esxi_hostname }}-localdatastore"
    path: ISO/linux_iso
    validate_certs: no
  delegate_to: localhost
  loop: "{{ esxi_servers }}"
  
- name: Copy VMware ISO to local ESXi datastore
  vsphere_copy:
    hostname: '{{ item.esxi_ip_address }}'
    username: '{{ item.esxi_username }}'
    password: '{{ item.esxi_password }}'
    src: /home/archiznix/git-novetta/autobuilder/ansible/roles/esxi_datastore/files/vmware_iso
    #datacenter: DC1 Someplace
    datastore: "{{ item.esxi_hostname }}-localdatastore"
    path: ISO/vmware_iso
    validate_certs: no
  delegate_to: localhost
  loop: "{{ esxi_servers }}"
  
- name: Copy Windows ISO to local ESXi datastore
  vsphere_copy:
    hostname: '{{ item.esxi_ip_address }}'
    username: '{{ item.esxi_username }}'
    password: '{{ item.esxi_password }}'
    src: /home/archiznix/git-novetta/autobuilder/ansible/roles/esxi_datastore/files/windows_iso
    #datacenter: DC1 Someplace
    datastore: "{{ item.esxi_hostname }}-localdatastore"
    path: ISO/windows_iso
    validate_certs: no
  delegate_to: localhost
  loop: "{{ esxi_servers }}"