---
# tasks file for firewall
- name: add http service to firewall
  firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['repo_server']

- name: add udp port 9995 to firewall
  firewalld:
    zone: public
    port: 9995/udp
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: add rich rules to firewall
  firewalld:
    zone: public
    rich_rule: '{{ item }}'
    permanent: yes
    state: enabled
  loop:
    - rule family="ipv4" source address="192.168.19.254/32" port port="22" protocol="tcp" accept
    - rule family="ipv4" source address="192.168.19.254/32" port port="514" protocol="udp" accept
    - rule family="ipv4" source address="192.168.16.0/22" port port="514" protocol="udp" accept
    - rule family="ipv4" source address="192.168.12.0/22" port port="514" protocol="udp" accept
    - rule family="ipv4" source address="192.168.12.0/22" port port="22" protocol="tcp" accept
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: remove services from firewall
  firewalld:
    service: '{{ item }}'
    permanent: yes
    state: absent
  loop:
    - dhcpv6-client
    - ssh
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']
