---
# tasks file for create_repo
- name: create repo directory
  file:
    path: /opt/repo
    state: directory
  when: inventory_hostname in groups['repo_servers']

#- name: copy repo tar files to remote host
#  copy:
#    src: '{{ item }}'
#    dest: /opt/repo
#  loop: '{{ repos|flatten(levels=1) }}'
#  when: inventory_hostname in groups['repo_servers']

#- name: extract repo files
#  unarchive:
#    src: '/opt/repo/{{ item }}'
#    dest: /
#    remote_src: yes
#  loop: '{{ repos|flatten(levels=1) }}'
#  when: inventory_hostname in groups['repo_servers']

- name: find current repo files
  find:
    paths: 
      - /etc/yum.repos.d
    patterns: '*.repo'
  register: repo_files

- name: remove current repo files
  file:
    path: '{{ item.path }}'
    state: absent
  loop: '{{ repo_files.files|flatten(levels=1) }}'

- name: local repo
  yum_repository:
    name: '{{ item.key | lower }}_local'
    description: 'CentOS-$releasever - {{ item.key }} Local'
    file: local
    baseurl: '{{ item.value.baseurl }}'
    gpgcheck: no
    enabled: yes
  loop: '{{ repo|dict2items }}'

- name: clean yum
  command:
    cmd: 'yum clean all'
    warn: no

- name: install httpd packages
  yum:
    name: '{{ packages }}'
    state: latest
  vars:
    packages:
      - httpd
      - mod_ssl
  when: inventory_hostname in groups['repo_servers']
      
- name: create certificate directory
  file:
    path: '{{ certificate_dir }}'
    state: directory
  when: inventory_hostname in groups['repo_servers']

- name: generate certificates # placeholder
  command: >
        openssl req -newkey rsa:2048 -nodes
        -keyout {{ certificate_dir }}/server.key
        -x509 -days 3650
        -out {{ certificate_dir }}/server.crt
        -subj '/C=US/ST=Florida/L=Tampa/CN=127.0.0.1'
  when: inventory_hostname in groups['repo_servers']

#- name: copy certificates
#  copy:
#    src: '{{ item }}'
#    dest: '{{ certificate_dir }}'
#  with_items:
#    - server.crt
#    - server.key
#    - server.ca
#  when: inventory_hostname in groups['repo_servers']

- name: create apache symlink
  file:
    src: /opt/repo/
    dest: /var/www/html/repo
    state: link
  when: inventory_hostname in groups['repo_servers']

- name: update ssl configuration
  template:
    src: ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname in groups['repo_servers']

- name: start apache
  service:
    name: httpd
    state: restarted
    enabled: yes
  notify: restart web
  when: inventory_hostname in groups['repo_servers']
