---
# tasks file for create_repo
- name: create repo directory
  file:
    path: /opt/repo
    state: directory
  when: inventory_hostname in groups['repo_servers']

- name: copy repo tar files to remote host
  copy:
    src: '{{ item }}'
    dest: /opt/repo
  with_items: '{{ repos }}'
  when: inventory_hostname in groups['repo_servers']

- name: extract repo files
  unarchive:
    src: '/opt/repo/{{ item }}'
    dest: /opt/repo
    remote_src: yes
  with_items: '{{ repos }}'
  when: inventory_hostname in groups['repo_servers']

- name: find current repo files
  find:
    paths: 
      - /etc/yum.repos.d
    patterns: '*.repo'
  register: repo_files

- name: remove current repo files
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ repo_files.files }}'
  notify: yum clean

- name: local repo
  yum_repository:
    name: '{{ item.key | lower }}_local'
    description: 'CentOS-$releasever - {{ item.key }} Local'
    file: local
    baseurl: '{{ item.value.baseurl }}'
    gpgcheck: no
    enabled: yes
  with_dict:
    - '{{ repo }}'
  notify: yum clean
