---
# tasks file for roles/win_adm_cfg
- name: Add administrator account
  win_user:
    name: "{{ win_admin }}"
    password: "{{ win_password }}"
    password_never_expires: true
    state: present
    groups:
      - Users
      - Administrators

- name: Ensure ansible account's password set to never expire
  win_user:
    name: ansible
    password_never_expires: true