---
- name: (create_repo) create repo directory
  file:
    path: /opt/repo
    state: directory
  when: inventory_hostname in groups['repo_server']

- name: (create_repo) extract repo files
  unarchive:
    src: '{{ item }}'
    dest: /opt/repo
  with_items:
    - base.tar.gz
    - epel.tar.gz
    - updates.tar.gz
    - extras.tar.gz
  when: inventory_hostname in groups['repo_server']

- name: (create_repo) find current repo files
  find:
    paths: 
      - /etc/yum.repos.d
    patterns: '*.repo'
  register: repo_files

- name: (create_repo) remove current repo files
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ repo_files.files }}'
  notify: yum clean

- name: (create_repo) local repo
  yum_repository:
    name: '{{ item.key|to_lower }}_local'
    description: 'CentOS-$releasever - {{ item.key }} Local'
    file: local
    baseurl: '{{ item.baseurl }}'
    gpgcheck: no
    enabled: yes
  with_dict:
    - '{{ repo }}'
  notify: yum clean
