---
- name: add http service to firewall
  firewalld:
    zone: public
    service: https
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['repo_server']

  - name: add udp port 9995 to firewall
  firewalld:
    zone: public
    port: 9995/udp
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: add rich rule to firewall (1/5)
  firewalld:
    zone: public
    rich_rule: rule family="ipv4" source address="192.168.19.254/32" port port="22" protocol="tcp" accept
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: add rich rule to firewall (2/5)
  firewalld:
    zone: public
    rich_rule: rule family="ipv4" source address="192.168.19.254/32" port port="514" protocol="udp" accept
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: add rich rule to firewall (3/5)
  firewalld:
    zone: public
    rich_rule: rule family="ipv4" source address="192.168.16.0/22" port port="514" protocol="udp" accept
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: add rich rule to firewall (4/5)
  firewalld:
    zone: public
    rich_rule: rule family="ipv4" source address="192.168.12.0/22" port port="514" protocol="udp" accept
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: add rich rule to firewall (5/5)
  firewalld:
    zone: public
    rich_rule: rule family="ipv4" source address="192.168.12.0/22" port port="22" protocol="tcp" accept
    permanent: yes
    state: enabled
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: remove dhcpv6 service from firewall
  firewalld:
    service: dhcpv6-client
    permanent: yes
    state: absent
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']

- name: remove ssh service from firewalld
  firewalld:
    service: ssh
    permanent: yes
    state: absent
  notify: restart firewall
  when: inventory_hostname in groups['syslog_server']
