---
- name: remove chrony
  yum:
    name: chronyd
    state: absent

- name: install ntp
  yum:
    name: ntp
    state: latest

- name: update ntp.conf
  template:
    source: ntp.conf.j2
    dest: /etc/ntp.conf
    backup: yes
  notify: restart ntpd