---
- name: update packages
  yum:
    name: '*'
    state: latest

- name: install packages
  yum:
    name: "{{ packages }}"
    state: latest

- name: remove packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - cups
      - postfix
