---
- name: (packages) update packages
  yum:
    name: '*'
    state: latest

- name: (packages) install packages
  yum:
    name: '{{ packages }}'
    state: latest

- name: (packages) remove packages
  yum:
    name: '{{ packages }}'
    state: absent
  vars:
    packages:
      - cups
      - postfix
