---
- name: (repo_web) create apache symlink
  file:
    src: /opt/repo/
    dest: /var/www/html/repo
    state: link

- name: (repo_web) start apache
  service:
    name: httpd
    state: restarted
    enabled: yes
  notify: restart web