---
- hosts: all

- include: repo_server.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == 7

- include: syslog_server.yml
  when: 
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == 7

- include: jump_boxes.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == 7
