---
- hosts: post_install
  any_errors_fatal: true
  tasks:
    - set_fact:
        packages: '{{ packages_all + packages_repo }}'

    - name: import role to configure disk partitions
      import_role:
        name: resize_partion
