---
# tasks file for roles/win_copy
- name: Copy software source files to host
  win_copy:
    src: /home/archiznix/windows/
    dest: C:\software

- name: Copy PowerCLI modules to PowerShell directory
  win_copy:
    src: /home/archiznix/windows/VMware.PowerCLI/
    dest: C:\Program Files\WindowsPowerShell\Modules